version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-docker
    restart: always
    networks: 
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: migration-system
    networks:
      - my_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: mydb 
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge